#!/bin/bash
python3 ./code/run_aan.py --train --NUM_EPOCHS 200 --BATCH_SIZE 128 --EVAL_FREQUENCY 25\
    --BETA_X 0.1\
    --BETA_X_CHANGE_RATE 1.2\
    --BETA_X_CHANGE_EPOCHS 10\
    --BETA_Y_LEAST 5\
    --BETA_Y_FAKE 5\
    --BETA_Y_CLEAN 1\
    --PIXEL_BOUND 64\
    --BOUND_CHANGE_RATE 0.8\
    --BOUND_CHANGE_EPOCHS 8\
    --EPSILON 128\
    --EPSILON_CHANGE_RATE 0.8\
    --EPSILON_CHANGE_EPOCHS 10\
    --FGM_ITERS 5
    