#!/bin/bash
python3 ./code/run_aan.py --train --NUM_EPOCHS 200 --BATCH_SIZE 128 --EVAL_FREQUENCY 25\
    --AE_TYPE TRAD\
    --EARLY_STOPPING_THRESHOLD 10\
    --BETA_X_TRUE 0.2\
    --BETA_X_TRUE_CHANGE_RATE 1.2\
    --BETA_X_TRUE_CHANGE_EPOCHS 8\
    --BETA_X_FAKE 0.1\
    --BETA_Y_TRANS 150\
    --BETA_Y_FAKE 0\
    --BETA_Y_FAKE_CHANGE_RATE 1.2\
    --BETA_Y_FAKE_CHANGE_EPOCHS 8\
    --BETA_Y_CLEAN 50\
    --PIXEL_BOUND 0.01\
    --BOUND_CHANGE_RATE 0.8\
    --BOUND_CHANGE_EPOCHS 8\
    --EPSILON 1\
    --FGM_ITERS 2